### ISSUE TITLE
Incorrect boss placement?

### ISSUE THREAD

**Issue by TrueEftekas** [mastermind1919/OctopathBossRandomizer#1]
Hello! I'd like to say that I appreciate the work you've done and I would like to say that I've been having a lot of fun with this.
That being said, on a seed that was not set to true random, with gate of finis bosses being in the pool, I got Dragon? as my chapter 2 boss for Alfyn. I'm not sure if this is intentional with the settings "Mix chapter 2-4 bosses" with "Include GoF bosses" combined meaning that GoF bosses are added to the chapter 4 pool, which is then added to the chapter 2-4 pool. If that is the case I believe the distinction should be made, if not, the seed number was 2869220569 and the settings are as shown in the image.

![image](https://user-images.githubusercontent.com/52509801/98529560-6f1bff80-2286-11eb-87f7-8d74a13c79cf.png)

Thanks for your hard work!

**Comment by mastermind1919** [comment]
This is completely intentional. What is happening is with all the include options, it adds those bosses to the chapter 4 pool, and then the mix chapter 2-4 bosses option allows for the chapter 4 boss pool to be spread out over the chapter 2-3 boss pools. I can definitely make it clearer that this is the case, wording hasn't been my strong suit to begin with (as you can probably tell with the "Force Tier Bosses" option).

**Comment by TrueEftekas** [comment]
Thanks for clarifying. I believe the wording should be "Include GoF bosses in the chapter 4 boss pool" in the description for "Include GoF bosses" and the "Mix chapter 2-4 Bosses" should say "Allows for Chapter 2 and 3 bosses to be mixed with the Chapter 4 boss pool", since "Chapter 4 bosses" implies the actual vanilla chapter 4 bosses.
Thanks again and I hope to see more features for this.
